site_name: ">>Anyget 説明書"
theme:
  name: material
  language: en
  palette:
    primary:  #efefef
    accent: #485269
  features:
    - tabs

plugins:
  - search:
      lang:
      - ja
      prebuild_index: true
      separator: '[\s\-\.]+'

extra_css:
  - extra_style.css

nav:
  - トップページ: index.md
  - チュートリアル:
    - 0. イントロダクション: Tutorial/00_Introduction.md
    - 1. 作業の流れ: Tutorial/01_Basic.md
    - 2. 投稿を操作する: Tutorial/02_Control.md
    - 3. テンプレートについて: Tutorial/03_Template.md
  - リファレンス:
    - メインパネル: Reference/MainPanel.md
    - サブパネル: Reference/SubPanels.md
    - テンプレート: Reference/Template.md
    - 設定: Reference/Settings.md
    - ショートカット: Reference/ShortCut.md